#!/usr/bin/env python3
"""
Script to translate tool descriptions from English to Spanish and Portuguese
"""

# Spanish translations
spanish_translations = {
    "uniswap": "Exchange descentralizado líder para intercambio de tokens",
    "aave": "Protocolo descentralizado de préstamos y empréstitos",
    "1inch": "Agregador DEX para los mejores precios de intercambio",
    "curve": "AMM enfocado en stablecoins con bajo deslizamiento",
    "dune": "Analíticas blockchain con consultas SQL personalizadas",
    "defillama": "Agregador de TVL DeFi y analíticas de protocolos",
    "nansen": "Analíticas on-chain con seguimiento de dinero inteligente",
    "arkham": "Plataforma de inteligencia blockchain",
    "revoke": "Gestionar y revocar aprobaciones de tokens",
    "debank": "Rastreador de portafolio multi-cadena y plataforma social",
    "pocket_universe": "Simulación de transacciones para seguridad",
    "across": "Puente cross-chain rápido y económico",
    "stargate": "Puente omnichain impulsado por LayerZero",
    "orbiter": "Puente cross-rollup L2",
    "etherscan": "Explorador blockchain de Ethereum",
    "blockscout": "Explorador de bloques de código abierto",
    "tenderly": "Tenderly - Depuración y monitoreo de contratos inteligentes",
    "chainlist": "Añadir redes EVM a tu wallet",
    "remix": "IDE Solidity basado en navegador",
    "opensea": "Mayor marketplace de NFT",
    "blur": "Marketplace NFT profesional para traders",
    "reservoir": "Infraestructura de liquidez NFT",
    "snapshot": "Votación de gobernanza off-chain sin gas",
    "tally": "Gobernanza on-chain y gestión de DAO",
    "biubiu_wallet_sweep": "Barrido masivo de tokens desde múltiples wallets",
    "biubiu_one_to_many": "Distribuir tokens a múltiples direcciones",
    "biubiu_wallet_generator": "Generar wallets HD con mnemónico",
    "biubiu_balance_scanner": "Escanear balances de tokens en múltiples wallets",
    "biubiu_contract_deployer": "Desplegar contratos inteligentes con CREATE2",
    "biubiu_token_deployer": "Desplegar tokens ERC-20 fácilmente",
    "biubiu_events_scanner": "Escanear y decodificar eventos de contratos",
    "biubiu_chainlist": "Explorar y añadir redes EVM",
    "lido": "Staking líquido para Ethereum y más",
    "compound": "Protocolo de mercado monetario algorítmico",
    "maker": "Protocolo de préstamos y stablecoin DAI",
    "gmx": "Exchange descentralizado de perpetuos",
    "pancakeswap": "DEX líder en BNB Chain",
    "sushiswap": "Plataforma DeFi y AMM multi-cadena",
    "balancer": "Gestor automatizado de portafolios y DEX",
    "eigenlayer": "Protocolo de restaking para seguridad de Ethereum",
    "magic_eden": "Marketplace NFT multi-cadena",
    "rarible": "Crear y comerciar NFT en cualquier cadena",
    "foundry": "Toolkit Solidity ultrarrápido",
    "hardhat": "Entorno de desarrollo de Ethereum",
    "slither": "Framework de análisis estático",
    "mythx": "API de seguridad para contratos inteligentes",
    "abi_ninja": "Interactuar con cualquier contrato inteligente",
    "4byte": "Base de datos de firmas de funciones de Ethereum",
    "token_terminal": "Métricas financieras para protocolos crypto",
    "ultrasound": "Rastreador de quema y suministro de ETH",
    "aragon": "Construir y gestionar DAOs fácilmente",
    "colony": "Infraestructura y nómina para DAOs",
    "dydx": "Exchange descentralizado de trading perpetuo",
    "convex": "Rendimientos Curve aumentados sin bloquear CRV",
    "yearn": "Bóvedas de optimización de rendimiento automatizadas",
    "pendle": "Tokenización y trading de rendimientos",
    "radiant": "Mercado monetario omnichain",
    "morpho": "Préstamos peer-to-peer con tasas optimizadas",
    "frax": "Stablecoin fraccional-algorítmica con colateralización parcial",
    "rocketpool": "Staking descentralizado de Ethereum",
    "venus": "Préstamos y empréstitos en BSC",
    "trader_joe": "DEX nativo de Avalanche",
    "camelot": "DEX nativo y launchpad de Arbitrum",
    "velodrome": "Hub de liquidez de Optimism",
    "aerodrome": "Hub central de liquidez para red Base",
    "maverick": "AMM de distribución dinámica para liquidez",
    "spark": "Protocolo de préstamos DAI por MakerDAO",
    "instadapp": "Agregador de cuenta inteligente DeFi",
    "sommelier": "Estrategias de bóveda DeFi gestionadas activamente",
    "hop": "Puente de tokens L2 a L2",
    "synapse": "Puente e intercambio cross-chain",
    "cbridge": "Puente cross-chain de Celer",
    "multichain": "Protocolo de enrutador multi-cadena",
    "wormhole": "Protocolo de mensajería cross-chain",
    "socket": "Agregador de puentes para mejores rutas",
    "rhino": "Agregador de puentes auto-custodiado",
    "arbiscan": "Explorador blockchain de Arbitrum",
    "optimistic_scan": "Explorador blockchain de Optimism",
    "polygonscan": "Explorador blockchain de Polygon",
    "bscscan": "Explorador blockchain de BNB Chain",
    "basescan": "Explorador blockchain de Base",
    "snowtrace": "Explorador blockchain de Avalanche",
    "zksync_explorer": "Explorador blockchain de zkSync Era",
    "lineascan": "Explorador blockchain de Linea",
    "l2beat": "Análisis de riesgo y TVL de Layer 2",
    "messari": "Plataforma de investigación y datos crypto",
    "coingecko": "Precios y datos de mercado de criptomonedas",
    "coinmarketcap": "Rankings de capitalización de mercado crypto",
    "glassnode": "Inteligencia de mercado on-chain",
    "santiment": "Métricas on-chain y sociales",
    "dexscreener": "Gráficos de pares DEX en tiempo real",
    "defined": "Analíticas DEX multi-cadena",
    "bubblemaps": "Análisis visual de distribución de holders y suministro de tokens",
    "certik": "Auditorías de seguridad y Skynet",
    "hacken": "Auditorías de seguridad blockchain",
    "immunefi": "Plataforma de bug bounty Web3",
    "openzeppelin": "Librería de seguridad para contratos inteligentes",
    "dedaub": "Herramientas de seguridad y decompilador para contratos inteligentes",
    "de_fi": "Escáner y herramientas de seguridad DeFi",
    "honeypot": "Detección de honeypot en tokens",
    "ethers": "Librería JavaScript de Ethereum",
    "viem": "Librería TypeScript de Ethereum",
    "wagmi": "Hooks de React para Ethereum",
    "rainbowkit": "UI de conexión de wallet en React",
    "web3modal": "Conexión de wallet multi-framework",
    "thirdweb": "Desarrollo Web3 full-stack",
    "alchemy": "Alchemy - Plataforma de desarrollo Web3 y APIs",
    "infura": "Infraestructura API de Ethereum",
    "quicknode": "Infraestructura de nodos multi-cadena",
    "solidity": "Documentación del lenguaje Solidity",
    "evm_codes": "Referencia de opcodes EVM y playground",
    "sourcify": "Verificación descentralizada de contratos",
    "rabby": "Wallet de navegador multi-cadena",
    "rainbow": "Hermosa wallet de Ethereum",
    "metamask": "Wallet Web3 más popular",
    "frame": "Wallet de escritorio enfocada en privacidad",
    "zerion": "Portafolio y wallet DeFi",
    "safe": "Wallet inteligente multi-firma",
    "phantom_wallet": "Wallet multi-cadena para Solana y Ethereum",
    "coinbase_wallet": "Wallet auto-custodiada de Coinbase",
    "trust_wallet": "Wallet móvil multi-cadena de Binance",
    "keplr_wallet": "Wallet del ecosistema Cosmos para cadenas IBC",
    "leap_wallet": "Wallet de Cosmos con soporte de staking",
    "okx_wallet": "Wallet multi-cadena del exchange OKX",
    "zapper": "Dashboard de portafolio DeFi",
    "zora": "Creación y marketplace de NFT",
    "foundation": "Marketplace de arte digital curado",
    "sound_xyz": "Plataforma NFT de música",
    "manifold": "Herramientas de creador y contratos NFT",
    "icy_tools": "Analíticas de mercado NFT",
    "nftnerds": "Trading y analíticas NFT",
    "boardroom": "Agregador de gobernanza para rastrear propuestas y votaciones de DAO",
    "karma": "Reputación de contribuidores DAO",
    "lenster": "Social descentralizado en Lens",
    "farcaster": "Protocolo social descentralizado",
    "pod_bankless": "Podcast DeFi sobre cultura y economía crypto",
    "pod_defiant": "Noticias y entrevistas enfocadas en DeFi",
    "pod_pomp": "Podcast de inversión en Bitcoin y crypto",
    "pod_epicenter": "Podcast blockchain desde 2013",
    "pod_real_vision": "Inversión macro y conocimientos crypto",
    "pod_bell_curve": "Análisis profundos de protocolos crypto",
    "pod_daily_gwei": "Noticias y análisis diarios de Ethereum",
    "pod_web3_galaxy": "Entrevistas y conocimientos de proyectos Web3",
    "push": "Notificaciones y chat Web3",
    "euler": "Protocolo de préstamos sin permisos",
    "benqi": "Préstamos y staking líquido en Avalanche",
    "silo": "Mercados de préstamos con riesgo aislado",
    "abracadabra": "Préstamos de tokens que generan intereses",
    "alchemix": "Protocolo de préstamos auto-reembolsables",
    "exactly": "Préstamos a tasa fija y variable",
    "kyberswap": "Agregador DEX con pools elásticos",
    "odos": "Agregador de enrutamiento inteligente de órdenes",
    "openocean": "Agregador DEX cross-chain",
    "hashflow": "Trading RFQ protegido contra MEV",
    "syncswap": "DEX nativo de zkSync Era",
    "mute": "DEX de zkSync con amplificador",
    "spacefi": "DEX y granja de rendimiento de zkSync",
    "ramses": "DEX ve(3,3) de Arbitrum",
    "thena": "DEX ve(3,3) de BNB Chain",
    "baseswap": "DEX y granja nativos de Base",
    "woofi": "DEX cross-chain con bajo deslizamiento",
    "gains": "Trading apalancado descentralizado",
    "level": "Plataforma de trading perpetuo",
    "mux": "Agregador de trading apalancado",
    "vertex": "DEX de perpetuos y spot",
    "hyperliquid": "DEX de orderbook perpetuo on-chain",
    "aevo": "Exchange de opciones y perpetuos",
    "lyra": "Protocolo AMM de opciones",
    "dopex": "Protocolo de opciones descentralizado",
    "premia": "Bóvedas y trading de opciones",
    "harvest": "Agregador de farming de rendimiento DeFi",
    "pickle": "Jarras de optimización de rendimiento",
    "concentrator": "Auto-composición para Curve y Convex",
    "conic": "Plataforma omnipool de Curve",
    "sturdy": "Protocolo de préstamos sin intereses",
    "stakewise": "Staking ETH no custodiado",
    "frax_ether": "Tokens de staking líquido de Frax",
    "stader": "Staking líquido multi-cadena",
    "mantle_lsp": "Protocolo de staking líquido de Mantle",
    "renzo": "Restaking líquido de EigenLayer",
    "etherfi": "Protocolo de staking descentralizado",
    "puffer": "Restaking líquido con tecnología anti-slashing",
    "kelp": "Restaking líquido con rsETH en EigenLayer",
    "hyphen": "Transferencias cross-chain instantáneas",
    "connext": "Puente cross-chain sin confianza",
    "debridge": "Interoperabilidad cross-chain",
    "allbridge": "Puente de stablecoin multi-cadena",
    "portal": "Puente Wormhole Portal",
    "squid": "Enrutador de intercambio cross-chain",
    "owlto": "Puente L2 rápido y económico",
    "scrollscan": "Explorador de red Scroll",
    "mantlescan": "Explorador de red Mantle",
    "blastscan": "Explorador de red Blast",
    "modescan": "Explorador de red Mode",
    "celoscan": "Explorador blockchain de Celo",
    "ftmscan": "Explorador de red Fantom",
    "gnosisscan": "Explorador de Gnosis Chain",
    "cronoscan": "Explorador de red Cronos",
    "moonbeamscan": "Explorador de Moonbeam y Moonriver",
    "tokenterminal": "Métricas financieras y de ingresos de protocolos",
    "artemis": "Analíticas e investigación crypto fundamental",
    "growthepie": "Analíticas y comparación de L2",
    "dappradar": "Ranking y rastreo de DApps",
    "ethburned": "Estadísticas de quema de Ethereum",
    "parsec": "Dashboard de analíticas DeFi",
    "eigenexplorer": "Explorador de analíticas de EigenLayer",
    "phalcon": "Explorador de análisis de transacciones",
    "tx_tracer": "Decodificador de traza de transacciones",
    "contract_diff": "Comparar versiones de contratos",
    "chainalysis": "Plataforma de cumplimiento blockchain",
    "brownie": "Framework de contratos inteligentes en Python",
    "ape": "Framework modular de Python",
    "pyth": "Oráculo de precios en tiempo real",
    "the_graph": "Protocolo descentralizado para indexación de datos blockchain",
    "goldsky": "Transmisión e indexación de datos blockchain en tiempo real",
    "envio": "HyperSync para indexación blockchain ultra rápida",
    "covalent": "API unificada de datos blockchain",
    "transpose": "Datos blockchain en tiempo real con API SQL",
    "chainbase": "Plataforma de datos todo en uno",
    "argent": "Wallet inteligente con recuperación",
    "sequence": "Wallet inteligente para gaming",
    "ledger": "Seguridad de wallet de hardware",
    "trezor": "Pionero de wallet de hardware",
    "privy": "Solución de wallet embebida",
    "dynamic": "Autenticación multi-wallet",
    "looksrare": "Marketplace NFT comunitario",
    "x2y2": "Marketplace NFT de bajas comisiones",
    "gem": "Agregador y barredor de NFT",
    "nftfi": "Préstamos colateralizados con NFT",
    "arcade": "Protocolo de préstamos NFT",
    "mintfun": "Descubrimiento de minteo de NFT",
    "daohaus": "Lanzador de DAO Moloch",
    "charmverse": "Plataforma de espacio de trabajo Web3",
    "wonderverse": "Wonderverse - Gestión de tareas DAO",
    "coordinape": "Compensación descentralizada",
    "guild": "Comunidades con acceso por tokens",
    "jokerace": "Concursos de votación on-chain",
    "ankr": "Endpoints RPC multi-cadena e infraestructura de staking",
    "chainstack": "Infraestructura blockchain gestionada para empresas",
    "blast_api": "Plataforma API descentralizada para constructores Web3",
    "chainlink": "Red de oráculo descentralizada líder para feeds de precio, VRF y automatización",
    "band_protocol": "Oráculo cross-chain con integración Cosmos SDK",
    "api3": "Oráculo de primera parte con Airnode para entrega directa de datos API",
    "redstone": "Oráculo modular para DeFi, LSDs y RWAs",
    "thegraph": "Protocolo de indexación para consultar datos blockchain",
    "subsquid": "SDK de indexación rápida de datos blockchain",
    "ipfs": "Almacenamiento descentralizado de archivos y direccionamiento de contenido",
    "arweave": "Almacenamiento descentralizado permanente de datos",
    "filecoin": "Red de almacenamiento descentralizada con incentivos",
    "ceramic": "Flujos de datos descentralizados y datos componibles",
    "push_protocol": "Notificaciones y mensajería nativas Web3",
    "xmtp": "Protocolo de mensajería segura wallet a wallet",
    "walletconnect": "Protocolo abierto para conectar wallets a DApps",
    "pump_fun": "Plataforma de lanzamiento justo para tokens meme en Solana",
    "dao_maker": "Launchpad IDO líder e incubadora",
    "fjord_foundry": "Pools de bootstrapping de liquidez para descubrimiento justo de precios",
    "camelot_launchpad": "Launchpad nativo del ecosistema Arbitrum",
    "pinksale": "Plataforma de preventa y lanzamiento justo multi-cadena",
    "gempad": "Launchpad cross-chain para preventas de tokens",
    "mint_fun": "Descubrir y mintear NFT en tendencia",
    "zora_create": "Mintear y crear NFT en el protocolo Zora",
    "thirdweb_deploy": "thirdweb Deploy - Despliegue de contratos sin código",
    "seedify": "Incubadora GameFi y launchpad IGO",
    "polkastarter": "Plataforma IDO cross-chain para gaming y DeFi",
    "ens": "Servicio de Nombres de Ethereum para direcciones legibles",
    "unstoppable_domains": "Dominios NFT para identidad Web3",
    "space_id": "Servicio de nombres de dominio multi-cadena",
    "dotbit": "Protocolo de identidad descentralizada cross-chain",
    "gitcoin_passport": "Verificación de identidad resistente a Sybil con sellos",
    "galxe": "Plataforma de credenciales y campañas Web3",
    "layer3": "Misiones de aprender para ganar y onboarding Web3",
    "degenscore": "Reputación on-chain y puntaje DeFi",
    "worldcoin": "Protocolo de identidad proof-of-personhood",
    "civic": "Soluciones de verificación de identidad y KYC",
    "poap": "Protocolo de Prueba de Asistencia para insignias de eventos",
    "talent_protocol": "Puntaje de constructor y reputación profesional",
    "lens_protocol": "Grafo social descentralizado componible",
    "warpcast": "Cliente principal para red social Farcaster",
    "hey": "App social descentralizada en Lens Protocol",
    "orb": "Cliente Lens Protocol enfocado en móviles",
    "cyberconnect": "Protocolo de grafo social con identidad Web3",
    "friend_tech": "Plataforma SocialFi para trading de claves sociales",
    "mirror": "Plataforma de publicación y crowdfunding Web3",
    "paragraph": "Boletín y publicación nativos Web3",
    "deso": "Blockchain Layer 1 construida para aplicaciones sociales",
    "phaver": "App social Web3 cross-platform",
    "drakula": "Plataforma de video de formato corto en Farcaster",
    "arbitrum_one": "Rollup optimista L2 líder de Ethereum",
    "optimism": "L2 de Ethereum impulsado por OP Stack con visión Superchain",
    "base": "L2 de Coinbase construida en OP Stack",
    "zksync_era": "ZK rollup con abstracción de cuenta nativa",
    "starknet": "ZK rollup usando Cairo para pruebas de validez",
    "scroll": "Rollup zkEVM equivalente a EVM",
    "linea": "Solución zkEVM L2 de ConsenSys",
    "polygon_zkevm": "Solución de escalado EVM de conocimiento cero de Polygon",
    "manta_pacific": "L2 modular para aplicaciones ZK",
    "blast_l2": "L2 con rendimiento nativo para ETH y stablecoins",
    "mode": "L2 OP Stack con enfoque DeFi",
    "mantle": "L2 modular con capa de disponibilidad de datos",
    "immutable": "L2 enfocado en gaming con zkEVM",
    "ronin": "Sidechain de gaming para ecosistema Axie Infinity",
    "treasure": "Ecosistema de gaming descentralizado en Arbitrum",
    "beam": "Subnet de gaming en Avalanche",
    "stardust": "SDK y solución de wallet para gaming Web3",
    "fractal": "Marketplace y descubrimiento de NFT gaming",
    "xai": "L3 de gaming construida en Arbitrum Orbit",
    "ygg": "Gremio de gaming con programas de becas",
    "loot8": "Plataforma de coleccionables de gaming NFT",
    "iskra": "Plataforma y comunidad de gaming Web3",
    "elixir_games": "Lanzador y plataforma de descubrimiento de juegos Web3",
    "moonpay": "On-ramp y off-ramp fiat para crypto",
    "transak": "Infraestructura de pago fiat a crypto",
    "ramp": "SDK de on-ramp fiat no custodiado",
    "onmeta": "On-ramp fiat para usuarios indios",
    "request_network": "Facturación crypto y solicitudes de pago",
    "superfluid": "Streaming de tokens en tiempo real para pagos",
    "sablier": "Streaming de tokens para vesting y nómina",
    "coinshift": "Gestión de tesorería y operaciones multi-sig",
    "utopia_labs": "Nómina DAO y operaciones de tesorería",
    "gnosis_pay": "Tarjeta de débito Visa auto-custodiada",
    "spritz": "Pagar facturas con crypto vía ACH",
    "bitpay": "Procesamiento de pagos crypto para comerciantes",
    "bentobox": "Bóveda de tokens de Sushi con préstamos flash y funciones de préstamo",
    "ribbon": "Productos estructurados y bóvedas de opciones para rendimiento sostenible",
    "opyn": "Protocolo de opciones con estrategia perpetua squeeth",
    "notional": "Protocolo de préstamos y empréstitos a tasa fija",
    "goldfinch": "Préstamos crypto para crédito del mundo real en mercados emergentes",
    "maple": "Mercado de préstamos subcolateralizados institucionales",
    "truefi": "Préstamos sin colateral para prestatarios institucionales",
    "tokemak": "Reactor de liquidez para liquidez DeFi sostenible",
    "olympus": "Protocolo de moneda de reserva descentralizada con token OHM",
    "jones_dao": "Bóvedas de opciones y estrategias de rendimiento en Arbitrum",
    "umami": "Bóvedas de rendimiento sostenible usando GLP en Arbitrum",
    "rage_trade": "Perpetuos y estrategias de rendimiento delta-neutral",
    "vela": "DEX perpetuo con características de trading avanzadas",
    "y2k": "Protocolo de seguro y cobertura de depeg de stablecoin",
    "kwenta": "Trading de futuros perpetuos en Synthetix",
    "polynomial": "Bóvedas de opciones impulsadas por Synthetix en Optimism",
    "angle": "Protocolo DeFi de stablecoin de euros y forex",
    "liquity": "Préstamos sin intereses contra ETH con stablecoin LUSD",
    "reflexer": "Stablecoin RAI no anclada con controlador PID",
    "mstable": "Plataforma de meta-stablecoin con ahorros de rendimiento",
    "raft": "Protocolo de préstamos de stablecoin respaldada por LSD",
    "prisma": "Stablecoin mkUSD respaldada por LSD con integración Curve",
    "gravita": "Préstamos de stablecoin GRAI respaldada por LSD",
    "gyroscope": "Stablecoin todo clima con reservas diversificadas",
    "origin_dollar": "Stablecoin que genera rendimiento con auto-composición",
    "paraswap": "Agregador DEX para mejores tasas de swap entre cadenas",
    "matcha": "Agregador DEX impulsado por protocolo 0x",
    "cowswap": "Swaps protegidos contra MEV con subastas por lotes",
    "bebop": "Swaps multi-token con trading sin gas",
    "dodo": "DEX de market maker proactivo con crowdpooling",
    "clipper": "DEX optimizado para traders minoristas y operaciones pequeñas",
    "woofi_pro": "Plataforma de trading perpetuo profesional",
    "sudoswap": "AMM NFT para liquidez y trading instantáneo",
    "caviar": "Protocolo de fraccionamiento y AMM de NFT",
    "nftx": "Protocolo de liquidez NFT con precios de piso en bóveda",
    "floor_protocol": "Fraccionamiento NFT en micro-tokens",
    "tessera": "Propiedad colectiva de NFT mediante fraccionamiento",
    "premint": "Herramienta de gestión de allowlist y whitelist de NFT",
    "bueno": "Herramienta de creación de arte NFT generativo sin código",
    "highlight": "Herramientas de creador para minteo y distribución de NFT",
    "transient_labs": "Herramientas de contrato inteligente para creadores NFT",
    "decent_xyz": "Minteo y puente de NFT cross-chain",
    "tokenproof": "Verificación NFT y experiencias con acceso por token",
    "delegate_cash": "Delegación NFT para uso seguro de hot wallet",
    "warm_xyz": "Vincular wallets frías y calientes para utilidad NFT",
    "layer3_quests": "Plataforma de misiones y credenciales de aprender para ganar",
    "rabbithole": "Misiones on-chain y obtención de credenciales",
    "flipside": "Analíticas blockchain con consultas SQL",
    "footprint": "Plataforma de análisis de datos blockchain sin código",
    "defi_pulse": "Rankings de TVL DeFi y analíticas de protocolos",
    "l2fees": "Comparar tarifas de transacción L2",
    "cryptofees": "Analíticas de tarifas y ingresos de protocolos",
    "openbb": "Terminal de investigación de inversión de código abierto",
    "watchers": "Rastreo y alertas de wallets whale",
    "cielo": "Rastreo de wallet social y feed de transacciones",
    "zerion_api": "SDK y API de rastreo de portafolio DeFi",
    "sim_farm": "Simulador de estrategia de farming de rendimiento DeFi",
    "hexagate": "Monitoreo de amenazas de contrato inteligente en tiempo real",
    "hypernative": "Monitoreo y prevención de seguridad impulsado por IA",
    "chainalert": "Alertas y notificaciones de seguridad blockchain",
    "webacy": "Respaldo de seguridad de wallet y herencia crypto",
    "harpie": "Firewall on-chain y protección anti-scam",
    "blowfish": "Simulación de transacciones y prevención de amenazas",
    "stelo": "Vistas previas de transacciones legibles para humanos",
    "fire": "Simulación de transacciones para protección de wallet",
    "wallet_guard": "Extensión de navegador para protección anti-phishing",
    "scamsniffer": "Servicio de detección de scams y phishing",
    "peckshield": "Firma de auditoría e investigación de seguridad blockchain",
    "slowmist": "Auditoría de seguridad e investigación de incidentes",
    "quantstamp": "Auditoría de seguridad blockchain empresarial",
    "consensys_diligence": "Herramientas de auditoría de seguridad de contratos inteligentes",
    "spearbit": "Red de investigadores de seguridad expertos",
    "scaffold_eth": "Kit de inicio para prototipado rápido de Ethereum",
    "create_eth_app": "CLI boilerplate para desarrollo de dApp React",
    "cookbook_dev": "Plantillas y registro de contratos inteligentes",
    "solidity_by_example": "Aprender Solidity mediante ejemplos de código",
    "speedrun_ethereum": "Desafíos interactivos de desarrollo Ethereum",
    "eth_build": "Sandbox de programación visual para Ethereum",
    "crypto_zombies": "Aprender Solidity construyendo un juego de zombies",
    "useweb3": "Recursos de aprendizaje Web3 curados",
    "buildspace": "Comunidad de aprendizaje Web3 basada en proyectos",
    "pointer": "Aprender desarrollo Web3 y ganar crypto",
    "chainide": "IDE de desarrollo multi-cadena basado en la nube",
    "atlas_ide": "IDE de desarrollo de circuitos ZK en la nube",
    "constructor": "Constructor de contratos inteligentes visual sin código",
    "bunzz": "Bunzz - Marketplace de despliegue de contratos inteligentes",
    "crossmint": "API de minteo NFT con pagos fiat",
    "paper_xyz": "Solución de checkout y minteo fiat de NFT",
    "li_fi": "Agregador de puentes e intercambios cross-chain",
    "bungee": "Agregador de puentes con función de recarga de gas",
    "jumper": "Agregador de puentes multi-cadena de LI.FI",
    "superbridge": "Puente nativo para Optimism y Base",
    "relay": "Solución de puente cross-chain instantáneo",
    "symbiosis": "Protocolo de liquidez cross-chain y DEX",
    "dln": "Trading cross-chain de órdenes limitadas DeBridge",
    "circle_cctp": "Protocolo de transferencia cross-chain USDC nativo",
    "ambire": "Wallet inteligente con login por email y transacciones sin gas",
    "obvious": "Wallet inteligente con abstracción de cuenta",
    "soul_wallet": "Wallet inteligente ERC-4337 modular",
    "patch_wallet": "Wallet inteligente embebida con login social",
    "pimlico": "Infraestructura de bundler y paymaster ERC-4337",
    "stackup": "Bundler y SDK de abstracción de cuenta",
    "biconomy": "SDK de abstracción de cuenta y transacciones sin gas",
    "alchemy_aa": "Toolkit de abstracción de cuenta de Alchemy",
    "zerodev": "SDK de wallet inteligente modular con Kernel",
    "particle_network": "Wallet-as-a-service con login social",
    "oklink": "Explorador blockchain multi-cadena de OKX",
    "routescan": "Explorador de bloques multi-cadena unificado",
    "onceupon": "Explorador de transacciones blockchain legible para humanos",
    "evm_explorer": "Explorador de bloques EVM multi-cadena",
    "anyabi": "Búsqueda y decodificador de ABI de contratos inteligentes",
    "samczsun_explorer": "Rastreador y depurador avanzado de transacciones",
    "commonwealth": "Foro de discusión y comunidad de gobernanza",
    "jokedao": "Concursos de votación on-chain y juegos de gobernanza",
    "nouns_builder": "Lanzar DAOs estilo Nouns con subastas diarias",
    "hats_protocol": "Gestión de roles y permisos DAO",
    "llama": "Gobernanza DAO y operaciones de tesorería",
    "utopia_dao": "Gestión de nómina y tesorería DAO",
    "grove": "Retransmisor RPC descentralizado impulsado por POKT",
    "drpc": "Proveedor RPC multi-cadena descentralizado",
    "nodies": "Infraestructura de nodos RPC multi-cadena",
    "llamanodes": "RPC enfocado en privacidad con protección MEV",
    "tenderly_node": "RPC con capacidades de simulación de transacciones",
    "getblock": "Acceso a nodos multi-cadena y proveedor RPC",
    "public_node": "Endpoints RPC públicos gratuitos",
    "flashbots_protect": "Endpoint RPC de protección MEV",
    "mev_blocker": "Protección MEV con reembolsos para usuarios",
    "bounce": "Plataforma de subasta descentralizada para tokens y NFT",
    "tokensoft": "Distribución de tokens y airdrops conformes",
    "hedgey": "Gestión de vesting y lockup de tokens",
    "magna": "Gestión de vesting de tokens y cap table",
    "superfluid_vesting": "Vesting de streaming continuo de tokens",
    "talentprotocol": "Plataforma de reputación y credenciales de constructores",
    "phi": "Identidad de metaverso y tierra de credenciales",
    "otterspace": "Insignias soulbound para membresía DAO",
    "disco": "Mochila de datos de credenciales verificables",
    "holonym": "Verificación de identidad preservando privacidad con ZK",
    "anima": "Identidad biométrica para resistencia sybil",
    "link3": "Eventos y credenciales Web3 de CyberConnect",
    "kiwi_news": "Agregador de noticias Web3 curado por comunidad",
    "orb_app": "Red social profesional en Lens",
    "buttrfly": "Agregador social cross-platform para Lens",
    "tape": "Plataforma de video descentralizada en Lens",
    "unlonely": "Plataforma comunitaria de streaming en vivo Web3",
    "l2_marathon": "Dashboard de analíticas y comparación de Layer 2",
    "chainlist_l2": "Añadir redes L2 a wallet con info RPC",
    "op_stack": "Framework modular para construir rollups L2",
    "orbit_chain": "Construir cadenas L3 personalizadas en Arbitrum",
    "polygon_cdk": "Kit de desarrollo de cadena impulsado por ZK",
    "zk_stack": "Framework de Hyperchain por zkSync",
    "loot": "Proyecto de equipo de aventura NFT componible",
    "pixels": "Juego de agricultura social en cadena Ronin",
    "parallel": "Juego de cartas coleccionables de ciencia ficción en Ethereum",
    "pirate_nation": "Aventura RPG de piratas completamente on-chain",
    "illuvium": "RPG auto-battler AAA en Immutable X",
    "shrapnel": "FPS de extracción modificable en Avalanche",
    "ev_io": "FPS basado en navegador con play-to-earn",
    "gnosis_card": "Tarjeta Visa auto-custodiada en Gnosis Chain",
    "holyheld": "Tarjeta de débito DeFi con funciones de rendimiento",
    "fusepay": "Tarjeta de gasto crypto en red Fuse",
    "loopcrypto": "Facturación y suscripciones crypto recurrentes",
    "reveel": "División automatizada de ingresos y regalías",
    "splits": "Protocolo de división de pagos on-chain",
    "four_meme": "Launchpad de monedas meme BNB Chain con lanzamiento justo",
    "sunpump": "Launchpad de monedas meme Tron con curva de vinculación",
    "moonshot": "Descubrimiento y trading de tokens meme Solana",
    "ape_store": "Plataforma de lanzamiento justo de monedas meme Ethereum",
    "believe": "Plataforma de lanzamiento de tokens sociales en Solana",
    "virtuals": "Plataforma de lanzamiento y gaming de tokens de agente IA",
    "clanker": "Lanzamiento de tokens nativo de Farcaster en Base",
    "dexscreener_moonshot": "Descubrimiento y analíticas de monedas meme en tendencia",
    "lfg_launchpad": "Plataforma oficial de lanzamiento de tokens de Jupiter",
    "starter": "Plataforma de IDO e incubadora multi-cadena",
    "impossible_finance": "Launchpad multi-cadena con niveles de staking",
    "gamefi_launchpad": "Plataforma IGO e IDO enfocada en gaming",
    "kommunitas": "Launchpad descentralizado impulsado por comunidad",
    "red_kite": "Launchpad multi-cadena de PolkaFoundry",
    "enjinstarter": "Launchpad de gaming y metaverso",
    "trustpad": "Launchpad multi-cadena con sistema de niveles",
    "spores": "Launchpad de NFT y tokens multi-cadena",
    "bullperks": "Launchpad multi-cadena respaldado por VC",
    "decubate": "IDO multi-cadena con vesting incorporado",
    "gagarin": "Launchpad del ecosistema TON vía Telegram",
    "tonstarter": "Launchpad premier para blockchain TON",
    "raydium_acceleraytor": "Plataforma de lanzamiento de tokens de Raydium en Solana",
    "meteora_dlmm": "Market maker de liquidez dinámica para lanzamientos de tokens",
    "orca_whirlpools": "Liquidez concentrada para lanzamientos de tokens Solana",
    "legion": "Launchpad Solana primero la comunidad",
    "armada": "Infraestructura de staking y validadores Solana",
    "streamflow": "Vesting de tokens y pagos por streaming",
    "vestinglab": "Infraestructura de vesting de tokens multi-cadena",
    "switchboard": "Oráculo descentralizado para cadenas Solana y Move",
    "dia": "Plataforma de oráculo transparente y personalizable",
    "tellor": "Oráculo sin permisos con mecanismo de disputa y staking",
    "symbiotic_restaking": "Protocolo de restaking modular sin permisos",
    "karak": "Restaking universal para seguridad multi-cadena",
    "ether_fi": "Restaking líquido no custodiado con eETH",
    "swell": "Staking y restaking líquido con swETH",
    "beefy": "Optimizador de rendimiento auto-compuesto multi-cadena",
    "equilibria": "Rendimientos aumentados para pools Pendle",
    "railgun": "DeFi privado con zk-SNARKs en cadenas EVM",
    "privacy_pools": "Protocolo de mezcla de transacciones preservando privacidad",
    "aztec": "Privacidad programable con zk-rollup",
    "nocturne": "Capa de cuenta privada para Ethereum",
    "umbra": "Pagos con direcciones ocultas en cadenas EVM",
    "labyrinth": "Privacidad conforme para instituciones",
    "elusiv": "Pagos privados conformes en Solana",
    "zcash": "Blockchain de privacidad nativa con transacciones blindadas",
    "space_and_time": "Almacén de datos verificable con pruebas ZK",
    "allium": "Plataforma de datos blockchain empresarial",
    "sentio": "Observabilidad y monitoreo multi-cadena",
    "tensor": "Trading NFT profesional en Solana",
    "hyperspace": "Agregador y marketplace NFT en Solana",
    "tradeport": "Marketplace NFT para Sui y Aptos",
    "campfire": "Marketplace NFT en Avalanche",
    "paintswap": "Marketplace NFT en Fantom y Sonic",
    "defillama_yields": "Comparación de farming de rendimiento cross-chain",
    "defilabs": "Rastreo de ballenas y dinero inteligente",
    "chainanalytics": "Dashboards de datos blockchain personalizados",
    "forta": "Red de detección de amenazas en tiempo real",
    "code4rena": "Concursos de auditoría impulsados por comunidad",
    "sherlock": "Concursos de auditoría con cobertura de exploits",
    "cookie3": "Cookie3 - Analíticas blockchain",
    "chainbeat": "ChainBeat - Analíticas blockchain",
    "bitquery": "Bitquery - Analíticas blockchain",
    "whale_alert": "Alertas de transacciones grandes en tiempo real entre blockchains",
    "intotheblock": "IntoTheBlock - Analíticas blockchain",
    "laevitas": "Laevitas - Analíticas blockchain",
    "kaiko": "Kaiko - Analíticas blockchain",
    "amberdata": "Amberdata - Analíticas blockchain",
    "blockpour": "Blockpour - Analíticas blockchain",
    "debridge_dln": "deBridge DLN - Puente cross-chain",
    "meson_finance": "Meson - Puente cross-chain",
    "layerswap": "Layerswap - Puente cross-chain",
    "router_protocol": "Router Protocol - Puente cross-chain",
    "nitro_bridge": "Nitro Bridge - Puente cross-chain",
    "portal_bridge_wormhole": "Portal Bridge - Puente cross-chain",
    "celer_im": "Celer IM - Puente cross-chain",
    "multichain_anycall": "Multichain AnyCall - Puente cross-chain",
    "hyperlane_bridge": "Hyperlane - Puente cross-chain",
    "connext_amarok": "Connext Amarok - Puente cross-chain"
}

# Portuguese translations
portuguese_translations = {
    "uniswap": "Exchange descentralizada líder para troca de tokens",
    "aave": "Protocolo descentralizado de empréstimos e empréstimos",
    "1inch": "Agregador DEX para melhores preços de troca",
    "curve": "AMM focado em stablecoins com baixo deslizamento",
    "dune": "Analíticas blockchain com consultas SQL personalizadas",
    "defillama": "Agregador de TVL DeFi e analíticas de protocolos",
    "nansen": "Analíticas on-chain com rastreamento de dinheiro inteligente",
    "arkham": "Plataforma de inteligência blockchain",
    "revoke": "Gerenciar e revogar aprovações de tokens",
    "debank": "Rastreador de portfólio multi-chain e plataforma social",
    "pocket_universe": "Simulação de transações para segurança",
    "across": "Ponte cross-chain rápida e econômica",
    "stargate": "Ponte omnichain alimentada por LayerZero",
    "orbiter": "Ponte cross-rollup L2",
    "etherscan": "Explorador blockchain de Ethereum",
    "blockscout": "Explorador de blocos de código aberto",
    "tenderly": "Tenderly - Depuração e monitoramento de contratos inteligentes",
    "chainlist": "Adicionar redes EVM à sua carteira",
    "remix": "IDE Solidity baseado em navegador",
    "opensea": "Maior marketplace de NFT",
    "blur": "Marketplace NFT profissional para traders",
    "reservoir": "Infraestrutura de liquidez NFT",
    "snapshot": "Votação de governança off-chain sem gas",
    "tally": "Governança on-chain e gestão de DAO",
    "biubiu_wallet_sweep": "Varredura em lote de tokens de múltiplas carteiras",
    "biubiu_one_to_many": "Distribuir tokens para múltiplos endereços",
    "biubiu_wallet_generator": "Gerar carteiras HD com mnemônico",
    "biubiu_balance_scanner": "Escanear saldos de tokens em múltiplas carteiras",
    "biubiu_contract_deployer": "Implantar contratos inteligentes com CREATE2",
    "biubiu_token_deployer": "Implantar tokens ERC-20 facilmente",
    "biubiu_events_scanner": "Escanear e decodificar eventos de contratos",
    "biubiu_chainlist": "Explorar e adicionar redes EVM",
    "lido": "Staking líquido para Ethereum e mais",
    "compound": "Protocolo de mercado monetário algorítmico",
    "maker": "Protocolo de empréstimos e stablecoin DAI",
    "gmx": "Exchange descentralizada de perpétuos",
    "pancakeswap": "DEX líder na BNB Chain",
    "sushiswap": "Plataforma DeFi e AMM multi-chain",
    "balancer": "Gestor automatizado de portfólios e DEX",
    "eigenlayer": "Protocolo de restaking para segurança do Ethereum",
    "magic_eden": "Marketplace NFT multi-chain",
    "rarible": "Criar e negociar NFT em qualquer chain",
    "foundry": "Toolkit Solidity ultra-rápido",
    "hardhat": "Ambiente de desenvolvimento Ethereum",
    "slither": "Framework de análise estática",
    "mythx": "API de segurança para contratos inteligentes",
    "abi_ninja": "Interagir com qualquer contrato inteligente",
    "4byte": "Base de dados de assinaturas de funções Ethereum",
    "token_terminal": "Métricas financeiras para protocolos crypto",
    "ultrasound": "Rastreador de queima e fornecimento de ETH",
    "aragon": "Construir e gerenciar DAOs facilmente",
    "colony": "Infraestrutura e folha de pagamento para DAOs",
    "dydx": "Exchange descentralizada de trading perpétuo",
    "convex": "Rendimentos Curve aumentados sem bloquear CRV",
    "yearn": "Cofres de otimização de rendimento automatizados",
    "pendle": "Tokenização e negociação de rendimentos",
    "radiant": "Mercado monetário omnichain",
    "morpho": "Empréstimos peer-to-peer com taxas otimizadas",
    "frax": "Stablecoin fracionária-algorítmica com colateralização parcial",
    "rocketpool": "Staking descentralizado de Ethereum",
    "venus": "Empréstimos e empréstimos na BSC",
    "trader_joe": "DEX nativo da Avalanche",
    "camelot": "DEX nativo e launchpad do Arbitrum",
    "velodrome": "Hub de liquidez do Optimism",
    "aerodrome": "Hub central de liquidez para rede Base",
    "maverick": "AMM de distribuição dinâmica para liquidez",
    "spark": "Protocolo de empréstimos DAI pela MakerDAO",
    "instadapp": "Agregador de conta inteligente DeFi",
    "sommelier": "Estratégias de cofre DeFi gerenciadas ativamente",
    "hop": "Ponte de tokens L2 para L2",
    "synapse": "Ponte e troca cross-chain",
    "cbridge": "Ponte cross-chain da Celer",
    "multichain": "Protocolo de roteador multi-chain",
    "wormhole": "Protocolo de mensagens cross-chain",
    "socket": "Agregador de pontes para melhores rotas",
    "rhino": "Agregador de pontes auto-custodial",
    "arbiscan": "Explorador blockchain do Arbitrum",
    "optimistic_scan": "Explorador blockchain do Optimism",
    "polygonscan": "Explorador blockchain do Polygon",
    "bscscan": "Explorador blockchain da BNB Chain",
    "basescan": "Explorador blockchain da Base",
    "snowtrace": "Explorador blockchain da Avalanche",
    "zksync_explorer": "Explorador blockchain do zkSync Era",
    "lineascan": "Explorador blockchain da Linea",
    "l2beat": "Análise de risco e TVL do Layer 2",
    "messari": "Plataforma de pesquisa e dados crypto",
    "coingecko": "Preços e dados de mercado de criptomoedas",
    "coinmarketcap": "Rankings de capitalização de mercado crypto",
    "glassnode": "Inteligência de mercado on-chain",
    "santiment": "Métricas on-chain e sociais",
    "dexscreener": "Gráficos de pares DEX em tempo real",
    "defined": "Analíticas DEX multi-chain",
    "bubblemaps": "Análise visual de distribuição de holders e fornecimento de tokens",
    "certik": "Auditorias de segurança e Skynet",
    "hacken": "Auditorias de segurança blockchain",
    "immunefi": "Plataforma de bug bounty Web3",
    "openzeppelin": "Biblioteca de segurança para contratos inteligentes",
    "dedaub": "Ferramentas de segurança e decompilador para contratos inteligentes",
    "de_fi": "Scanner e ferramentas de segurança DeFi",
    "honeypot": "Detecção de honeypot em tokens",
    "ethers": "Biblioteca JavaScript do Ethereum",
    "viem": "Biblioteca TypeScript do Ethereum",
    "wagmi": "Hooks do React para Ethereum",
    "rainbowkit": "UI de conexão de carteira em React",
    "web3modal": "Conexão de carteira multi-framework",
    "thirdweb": "Desenvolvimento Web3 full-stack",
    "alchemy": "Alchemy - Plataforma de desenvolvimento Web3 e APIs",
    "infura": "Infraestrutura API do Ethereum",
    "quicknode": "Infraestrutura de nós multi-chain",
    "solidity": "Documentação da linguagem Solidity",
    "evm_codes": "Referência de opcodes EVM e playground",
    "sourcify": "Verificação descentralizada de contratos",
    "rabby": "Carteira de navegador multi-chain",
    "rainbow": "Bela carteira Ethereum",
    "metamask": "Carteira Web3 mais popular",
    "frame": "Carteira de desktop focada em privacidade",
    "zerion": "Portfólio e carteira DeFi",
    "safe": "Carteira inteligente multi-assinatura",
    "phantom_wallet": "Carteira multi-chain para Solana e Ethereum",
    "coinbase_wallet": "Carteira auto-custodial da Coinbase",
    "trust_wallet": "Carteira móvel multi-chain da Binance",
    "keplr_wallet": "Carteira do ecossistema Cosmos para chains IBC",
    "leap_wallet": "Carteira Cosmos com suporte de staking",
    "okx_wallet": "Carteira multi-chain da exchange OKX",
    "zapper": "Dashboard de portfólio DeFi",
    "zora": "Criação e marketplace de NFT",
    "foundation": "Marketplace de arte digital curado",
    "sound_xyz": "Plataforma NFT de música",
    "manifold": "Ferramentas de criador e contratos NFT",
    "icy_tools": "Analíticas de mercado NFT",
    "nftnerds": "Negociação e analíticas NFT",
    "boardroom": "Agregador de governança para rastrear propostas e votações de DAO",
    "karma": "Reputação de contribuidores DAO",
    "lenster": "Social descentralizado no Lens",
    "farcaster": "Protocolo social descentralizado",
    "pod_bankless": "Podcast DeFi sobre cultura e economia crypto",
    "pod_defiant": "Notícias e entrevistas focadas em DeFi",
    "pod_pomp": "Podcast de investimento em Bitcoin e crypto",
    "pod_epicenter": "Podcast blockchain desde 2013",
    "pod_real_vision": "Investimento macro e insights crypto",
    "pod_bell_curve": "Análises profundas de protocolos crypto",
    "pod_daily_gwei": "Notícias e análises diárias do Ethereum",
    "pod_web3_galaxy": "Entrevistas e insights de projetos Web3",
    "push": "Notificações e chat Web3",
    "euler": "Protocolo de empréstimos sem permissões",
    "benqi": "Empréstimos e staking líquido na Avalanche",
    "silo": "Mercados de empréstimos com risco isolado",
    "abracadabra": "Empréstimos de tokens que geram juros",
    "alchemix": "Protocolo de empréstimos auto-reembolsáveis",
    "exactly": "Empréstimos a taxa fixa e variável",
    "kyberswap": "Agregador DEX com pools elásticos",
    "odos": "Agregador de roteamento inteligente de ordens",
    "openocean": "Agregador DEX cross-chain",
    "hashflow": "Negociação RFQ protegida contra MEV",
    "syncswap": "DEX nativo do zkSync Era",
    "mute": "DEX do zkSync com amplificador",
    "spacefi": "DEX e fazenda de rendimento do zkSync",
    "ramses": "DEX ve(3,3) do Arbitrum",
    "thena": "DEX ve(3,3) da BNB Chain",
    "baseswap": "DEX e fazenda nativos da Base",
    "woofi": "DEX cross-chain com baixo deslizamento",
    "gains": "Negociação alavancada descentralizada",
    "level": "Plataforma de negociação perpétua",
    "mux": "Agregador de negociação alavancada",
    "vertex": "DEX de perpétuos e spot",
    "hyperliquid": "DEX de orderbook perpétuo on-chain",
    "aevo": "Exchange de opções e perpétuos",
    "lyra": "Protocolo AMM de opções",
    "dopex": "Protocolo de opções descentralizado",
    "premia": "Cofres e negociação de opções",
    "harvest": "Agregador de farming de rendimento DeFi",
    "pickle": "Jarros de otimização de rendimento",
    "concentrator": "Auto-composição para Curve e Convex",
    "conic": "Plataforma omnipool da Curve",
    "sturdy": "Protocolo de empréstimos sem juros",
    "stakewise": "Staking ETH não-custodial",
    "frax_ether": "Tokens de staking líquido da Frax",
    "stader": "Staking líquido multi-chain",
    "mantle_lsp": "Protocolo de staking líquido da Mantle",
    "renzo": "Restaking líquido do EigenLayer",
    "etherfi": "Protocolo de staking descentralizado",
    "puffer": "Restaking líquido com tecnologia anti-slashing",
    "kelp": "Restaking líquido com rsETH no EigenLayer",
    "hyphen": "Transferências cross-chain instantâneas",
    "connext": "Ponte cross-chain sem confiança",
    "debridge": "Interoperabilidade cross-chain",
    "allbridge": "Ponte de stablecoin multi-chain",
    "portal": "Ponte Wormhole Portal",
    "squid": "Roteador de troca cross-chain",
    "owlto": "Ponte L2 rápida e econômica",
    "scrollscan": "Explorador de rede Scroll",
    "mantlescan": "Explorador de rede Mantle",
    "blastscan": "Explorador de rede Blast",
    "modescan": "Explorador de rede Mode",
    "celoscan": "Explorador blockchain da Celo",
    "ftmscan": "Explorador de rede Fantom",
    "gnosisscan": "Explorador da Gnosis Chain",
    "cronoscan": "Explorador de rede Cronos",
    "moonbeamscan": "Explorador do Moonbeam e Moonriver",
    "tokenterminal": "Métricas financeiras e de receita de protocolos",
    "artemis": "Analíticas e pesquisa crypto fundamental",
    "growthepie": "Analíticas e comparação de L2",
    "dappradar": "Ranking e rastreamento de DApps",
    "ethburned": "Estatísticas de queima do Ethereum",
    "parsec": "Dashboard de analíticas DeFi",
    "eigenexplorer": "Explorador de analíticas do EigenLayer",
    "phalcon": "Explorador de análise de transações",
    "tx_tracer": "Decodificador de rastreamento de transações",
    "contract_diff": "Comparar versões de contratos",
    "chainalysis": "Plataforma de conformidade blockchain",
    "brownie": "Framework de contratos inteligentes em Python",
    "ape": "Framework modular de Python",
    "pyth": "Oráculo de preços em tempo real",
    "the_graph": "Protocolo descentralizado para indexação de dados blockchain",
    "goldsky": "Transmissão e indexação de dados blockchain em tempo real",
    "envio": "HyperSync para indexação blockchain ultra-rápida",
    "covalent": "API unificada de dados blockchain",
    "transpose": "Dados blockchain em tempo real com API SQL",
    "chainbase": "Plataforma de dados tudo-em-um",
    "argent": "Carteira inteligente com recuperação",
    "sequence": "Carteira inteligente para gaming",
    "ledger": "Segurança de carteira de hardware",
    "trezor": "Pioneiro de carteira de hardware",
    "privy": "Solução de carteira embutida",
    "dynamic": "Autenticação multi-carteira",
    "looksrare": "Marketplace NFT comunitário",
    "x2y2": "Marketplace NFT de baixas taxas",
    "gem": "Agregador e varredor de NFT",
    "nftfi": "Empréstimos colateralizados com NFT",
    "arcade": "Protocolo de empréstimos NFT",
    "mintfun": "Descoberta de cunhagem de NFT",
    "daohaus": "Lançador de DAO Moloch",
    "charmverse": "Plataforma de espaço de trabalho Web3",
    "wonderverse": "Wonderverse - Gestão de tarefas DAO",
    "coordinape": "Compensação descentralizada",
    "guild": "Comunidades com acesso por tokens",
    "jokerace": "Concursos de votação on-chain",
    "ankr": "Endpoints RPC multi-chain e infraestrutura de staking",
    "chainstack": "Infraestrutura blockchain gerenciada para empresas",
    "blast_api": "Plataforma API descentralizada para construtores Web3",
    "chainlink": "Rede de oráculo descentralizada líder para feeds de preço, VRF e automação",
    "band_protocol": "Oráculo cross-chain com integração Cosmos SDK",
    "api3": "Oráculo de primeira parte com Airnode para entrega direta de dados API",
    "redstone": "Oráculo modular para DeFi, LSDs e RWAs",
    "thegraph": "Protocolo de indexação para consultar dados blockchain",
    "subsquid": "SDK de indexação rápida de dados blockchain",
    "ipfs": "Armazenamento descentralizado de arquivos e endereçamento de conteúdo",
    "arweave": "Armazenamento descentralizado permanente de dados",
    "filecoin": "Rede de armazenamento descentralizada com incentivos",
    "ceramic": "Fluxos de dados descentralizados e dados componíveis",
    "push_protocol": "Notificações e mensagens nativas Web3",
    "xmtp": "Protocolo de mensagens seguras carteira para carteira",
    "walletconnect": "Protocolo aberto para conectar carteiras a DApps",
    "pump_fun": "Plataforma de lançamento justo para tokens meme no Solana",
    "dao_maker": "Launchpad IDO líder e incubadora",
    "fjord_foundry": "Pools de bootstrapping de liquidez para descoberta justa de preços",
    "camelot_launchpad": "Launchpad nativo do ecossistema Arbitrum",
    "pinksale": "Plataforma de pré-venda e lançamento justo multi-chain",
    "gempad": "Launchpad cross-chain para pré-vendas de tokens",
    "mint_fun": "Descobrir e cunhar NFT em tendência",
    "zora_create": "Cunhar e criar NFT no protocolo Zora",
    "thirdweb_deploy": "thirdweb Deploy - Implantação de contratos sem código",
    "seedify": "Incubadora GameFi e launchpad IGO",
    "polkastarter": "Plataforma IDO cross-chain para gaming e DeFi",
    "ens": "Serviço de Nomes Ethereum para endereços legíveis",
    "unstoppable_domains": "Domínios NFT para identidade Web3",
    "space_id": "Serviço de nomes de domínio multi-chain",
    "dotbit": "Protocolo de identidade descentralizada cross-chain",
    "gitcoin_passport": "Verificação de identidade resistente a Sybil com selos",
    "galxe": "Plataforma de credenciais e campanhas Web3",
    "layer3": "Missões de aprender para ganhar e onboarding Web3",
    "degenscore": "Reputação on-chain e pontuação DeFi",
    "worldcoin": "Protocolo de identidade proof-of-personhood",
    "civic": "Soluções de verificação de identidade e KYC",
    "poap": "Protocolo de Prova de Presença para emblemas de eventos",
    "talent_protocol": "Pontuação de construtor e reputação profissional",
    "lens_protocol": "Grafo social descentralizado componível",
    "warpcast": "Cliente principal para rede social Farcaster",
    "hey": "App social descentralizado no Lens Protocol",
    "orb": "Cliente Lens Protocol focado em móveis",
    "cyberconnect": "Protocolo de grafo social com identidade Web3",
    "friend_tech": "Plataforma SocialFi para negociação de chaves sociais",
    "mirror": "Plataforma de publicação e crowdfunding Web3",
    "paragraph": "Newsletter e publicação nativos Web3",
    "deso": "Blockchain Layer 1 construída para aplicações sociais",
    "phaver": "App social Web3 cross-platform",
    "drakula": "Plataforma de vídeo de formato curto no Farcaster",
    "arbitrum_one": "Rollup otimista L2 líder do Ethereum",
    "optimism": "L2 do Ethereum alimentado por OP Stack com visão Superchain",
    "base": "L2 da Coinbase construída em OP Stack",
    "zksync_era": "ZK rollup com abstração de conta nativa",
    "starknet": "ZK rollup usando Cairo para provas de validade",
    "scroll": "Rollup zkEVM equivalente a EVM",
    "linea": "Solução zkEVM L2 da ConsenSys",
    "polygon_zkevm": "Solução de escalabilidade EVM de conhecimento zero do Polygon",
    "manta_pacific": "L2 modular para aplicações ZK",
    "blast_l2": "L2 com rendimento nativo para ETH e stablecoins",
    "mode": "L2 OP Stack com foco DeFi",
    "mantle": "L2 modular com camada de disponibilidade de dados",
    "immutable": "L2 focado em gaming com zkEVM",
    "ronin": "Sidechain de gaming para ecossistema Axie Infinity",
    "treasure": "Ecossistema de gaming descentralizado no Arbitrum",
    "beam": "Subnet de gaming na Avalanche",
    "stardust": "SDK e solução de carteira para gaming Web3",
    "fractal": "Marketplace e descoberta de NFT gaming",
    "xai": "L3 de gaming construída em Arbitrum Orbit",
    "ygg": "Guilda de gaming com programas de bolsas",
    "loot8": "Plataforma de colecionáveis de gaming NFT",
    "iskra": "Plataforma e comunidade de gaming Web3",
    "elixir_games": "Lançador e plataforma de descoberta de jogos Web3",
    "moonpay": "On-ramp e off-ramp fiat para crypto",
    "transak": "Infraestrutura de pagamento fiat para crypto",
    "ramp": "SDK de on-ramp fiat não-custodial",
    "onmeta": "On-ramp fiat para usuários indianos",
    "request_network": "Faturamento crypto e solicitações de pagamento",
    "superfluid": "Streaming de tokens em tempo real para pagamentos",
    "sablier": "Streaming de tokens para vesting e folha de pagamento",
    "coinshift": "Gestão de tesouraria e operações multi-sig",
    "utopia_labs": "Folha de pagamento DAO e operações de tesouraria",
    "gnosis_pay": "Cartão de débito Visa auto-custodial",
    "spritz": "Pagar contas com crypto via ACH",
    "bitpay": "Processamento de pagamentos crypto para comerciantes",
    "bentobox": "Cofre de tokens do Sushi com empréstimos flash e funções de empréstimo",
    "ribbon": "Produtos estruturados e cofres de opções para rendimento sustentável",
    "opyn": "Protocolo de opções com estratégia perpétua squeeth",
    "notional": "Protocolo de empréstimos e empréstimos a taxa fixa",
    "goldfinch": "Empréstimos crypto para crédito do mundo real em mercados emergentes",
    "maple": "Mercado de empréstimos subcolateralizados institucional",
    "truefi": "Empréstimos sem colateral para tomadores institucionais",
    "tokemak": "Reator de liquidez para liquidez DeFi sustentável",
    "olympus": "Protocolo de moeda de reserva descentralizada com token OHM",
    "jones_dao": "Cofres de opções e estratégias de rendimento no Arbitrum",
    "umami": "Cofres de rendimento sustentável usando GLP no Arbitrum",
    "rage_trade": "Perpétuos e estratégias de rendimento delta-neutral",
    "vela": "DEX perpétuo com recursos de negociação avançados",
    "y2k": "Protocolo de seguro e cobertura de depeg de stablecoin",
    "kwenta": "Negociação de futuros perpétuos no Synthetix",
    "polynomial": "Cofres de opções alimentados por Synthetix no Optimism",
    "angle": "Protocolo DeFi de stablecoin de euros e forex",
    "liquity": "Empréstimos sem juros contra ETH com stablecoin LUSD",
    "reflexer": "Stablecoin RAI não-ancorada com controlador PID",
    "mstable": "Plataforma de meta-stablecoin com poupanças de rendimento",
    "raft": "Protocolo de empréstimos de stablecoin apoiada por LSD",
    "prisma": "Stablecoin mkUSD apoiada por LSD com integração Curve",
    "gravita": "Empréstimos de stablecoin GRAI apoiada por LSD",
    "gyroscope": "Stablecoin para todos os climas com reservas diversificadas",
    "origin_dollar": "Stablecoin que gera rendimento com auto-composição",
    "paraswap": "Agregador DEX para melhores taxas de swap entre chains",
    "matcha": "Agregador DEX alimentado por protocolo 0x",
    "cowswap": "Swaps protegidos contra MEV com leilões em lote",
    "bebop": "Swaps multi-token com negociação sem gas",
    "dodo": "DEX de market maker proativo com crowdpooling",
    "clipper": "DEX otimizado para traders de varejo e operações pequenas",
    "woofi_pro": "Plataforma de negociação perpétua profissional",
    "sudoswap": "AMM NFT para liquidez e negociação instantânea",
    "caviar": "Protocolo de fracionamento e AMM de NFT",
    "nftx": "Protocolo de liquidez NFT com preços de piso em cofre",
    "floor_protocol": "Fracionamento NFT em micro-tokens",
    "tessera": "Propriedade coletiva de NFT através de fracionamento",
    "premint": "Ferramenta de gestão de allowlist e whitelist de NFT",
    "bueno": "Ferramenta de criação de arte NFT generativa sem código",
    "highlight": "Ferramentas de criador para cunhagem e distribuição de NFT",
    "transient_labs": "Ferramentas de contrato inteligente para criadores NFT",
    "decent_xyz": "Cunhagem e ponte de NFT cross-chain",
    "tokenproof": "Verificação NFT e experiências com acesso por token",
    "delegate_cash": "Delegação NFT para uso seguro de hot wallet",
    "warm_xyz": "Vincular carteiras frias e quentes para utilidade NFT",
    "layer3_quests": "Plataforma de missões e credenciais de aprender para ganhar",
    "rabbithole": "Missões on-chain e obtenção de credenciais",
    "flipside": "Analíticas blockchain com consultas SQL",
    "footprint": "Plataforma de análise de dados blockchain sem código",
    "defi_pulse": "Rankings de TVL DeFi e analíticas de protocolos",
    "l2fees": "Comparar taxas de transação L2",
    "cryptofees": "Analíticas de taxas e receita de protocolos",
    "openbb": "Terminal de pesquisa de investimento de código aberto",
    "watchers": "Rastreamento e alertas de carteiras whale",
    "cielo": "Rastreamento de carteira social e feed de transações",
    "zerion_api": "SDK e API de rastreamento de portfólio DeFi",
    "sim_farm": "Simulador de estratégia de farming de rendimento DeFi",
    "hexagate": "Monitoramento de ameaças de contrato inteligente em tempo real",
    "hypernative": "Monitoramento e prevenção de segurança alimentado por IA",
    "chainalert": "Alertas e notificações de segurança blockchain",
    "webacy": "Backup de segurança de carteira e herança crypto",
    "harpie": "Firewall on-chain e proteção anti-scam",
    "blowfish": "Simulação de transações e prevenção de ameaças",
    "stelo": "Visualizações prévias de transações legíveis para humanos",
    "fire": "Simulação de transações para proteção de carteira",
    "wallet_guard": "Extensão de navegador para proteção anti-phishing",
    "scamsniffer": "Serviço de detecção de scams e phishing",
    "peckshield": "Firma de auditoria e pesquisa de segurança blockchain",
    "slowmist": "Auditoria de segurança e investigação de incidentes",
    "quantstamp": "Auditoria de segurança blockchain empresarial",
    "consensys_diligence": "Ferramentas de auditoria de segurança de contratos inteligentes",
    "spearbit": "Rede de pesquisadores de segurança especialistas",
    "scaffold_eth": "Kit de início para prototipagem rápida de Ethereum",
    "create_eth_app": "CLI boilerplate para desenvolvimento de dApp React",
    "cookbook_dev": "Modelos e registro de contratos inteligentes",
    "solidity_by_example": "Aprender Solidity através de exemplos de código",
    "speedrun_ethereum": "Desafios interativos de desenvolvimento Ethereum",
    "eth_build": "Sandbox de programação visual para Ethereum",
    "crypto_zombies": "Aprender Solidity construindo um jogo de zumbis",
    "useweb3": "Recursos de aprendizagem Web3 curados",
    "buildspace": "Comunidade de aprendizagem Web3 baseada em projetos",
    "pointer": "Aprender desenvolvimento Web3 e ganhar crypto",
    "chainide": "IDE de desenvolvimento multi-chain baseado em nuvem",
    "atlas_ide": "IDE de desenvolvimento de circuitos ZK em nuvem",
    "constructor": "Construtor de contratos inteligentes visual sem código",
    "bunzz": "Bunzz - Marketplace de implantação de contratos inteligentes",
    "crossmint": "API de cunhagem NFT com pagamentos fiat",
    "paper_xyz": "Solução de checkout e cunhagem fiat de NFT",
    "li_fi": "Agregador de pontes e trocas cross-chain",
    "bungee": "Agregador de pontes com função de recarga de gas",
    "jumper": "Agregador de pontes multi-chain da LI.FI",
    "superbridge": "Ponte nativa para Optimism e Base",
    "relay": "Solução de ponte cross-chain instantânea",
    "symbiosis": "Protocolo de liquidez cross-chain e DEX",
    "dln": "Negociação cross-chain de ordens limitadas DeBridge",
    "circle_cctp": "Protocolo de transferência cross-chain USDC nativo",
    "ambire": "Carteira inteligente com login por email e transações sem gas",
    "obvious": "Carteira inteligente com abstração de conta",
    "soul_wallet": "Carteira inteligente ERC-4337 modular",
    "patch_wallet": "Carteira inteligente embutida com login social",
    "pimlico": "Infraestrutura de bundler e paymaster ERC-4337",
    "stackup": "Bundler e SDK de abstração de conta",
    "biconomy": "SDK de abstração de conta e transações sem gas",
    "alchemy_aa": "Toolkit de abstração de conta da Alchemy",
    "zerodev": "SDK de carteira inteligente modular com Kernel",
    "particle_network": "Carteira-como-serviço com login social",
    "oklink": "Explorador blockchain multi-chain da OKX",
    "routescan": "Explorador de blocos multi-chain unificado",
    "onceupon": "Explorador de transações blockchain legível para humanos",
    "evm_explorer": "Explorador de blocos EVM multi-chain",
    "anyabi": "Busca e decodificador de ABI de contratos inteligentes",
    "samczsun_explorer": "Rastreador e depurador avançado de transações",
    "commonwealth": "Fórum de discussão e comunidade de governança",
    "jokedao": "Concursos de votação on-chain e jogos de governança",
    "nouns_builder": "Lançar DAOs estilo Nouns com leilões diários",
    "hats_protocol": "Gestão de funções e permissões DAO",
    "llama": "Governança DAO e operações de tesouraria",
    "utopia_dao": "Gestão de folha de pagamento e tesouraria DAO",
    "grove": "Retransmissor RPC descentralizado alimentado por POKT",
    "drpc": "Provedor RPC multi-chain descentralizado",
    "nodies": "Infraestrutura de nós RPC multi-chain",
    "llamanodes": "RPC focado em privacidade com proteção MEV",
    "tenderly_node": "RPC com capacidades de simulação de transações",
    "getblock": "Acesso a nós multi-chain e provedor RPC",
    "public_node": "Endpoints RPC públicos gratuitos",
    "flashbots_protect": "Endpoint RPC de proteção MEV",
    "mev_blocker": "Proteção MEV com reembolsos para usuários",
    "bounce": "Plataforma de leilão descentralizada para tokens e NFT",
    "tokensoft": "Distribuição de tokens e airdrops conformes",
    "hedgey": "Gestão de vesting e lockup de tokens",
    "magna": "Gestão de vesting de tokens e cap table",
    "superfluid_vesting": "Vesting de streaming contínuo de tokens",
    "talentprotocol": "Plataforma de reputação e credenciais de construtores",
    "phi": "Identidade de metaverso e terra de credenciais",
    "otterspace": "Emblemas soulbound para membros DAO",
    "disco": "Mochila de dados de credenciais verificáveis",
    "holonym": "Verificação de identidade preservando privacidade com ZK",
    "anima": "Identidade biométrica para resistência sybil",
    "link3": "Eventos e credenciais Web3 da CyberConnect",
    "kiwi_news": "Agregador de notícias Web3 curado por comunidade",
    "orb_app": "Rede social profissional no Lens",
    "buttrfly": "Agregador social cross-platform para Lens",
    "tape": "Plataforma de vídeo descentralizada no Lens",
    "unlonely": "Plataforma comunitária de streaming ao vivo Web3",
    "l2_marathon": "Dashboard de analíticas e comparação de Layer 2",
    "chainlist_l2": "Adicionar redes L2 à carteira com info RPC",
    "op_stack": "Framework modular para construir rollups L2",
    "orbit_chain": "Construir chains L3 personalizadas no Arbitrum",
    "polygon_cdk": "Kit de desenvolvimento de chain alimentado por ZK",
    "zk_stack": "Framework de Hyperchain pelo zkSync",
    "loot": "Projeto de equipamento de aventura NFT componível",
    "pixels": "Jogo de agricultura social na chain Ronin",
    "parallel": "Jogo de cartas colecionáveis de ficção científica no Ethereum",
    "pirate_nation": "Aventura RPG de piratas totalmente on-chain",
    "illuvium": "RPG auto-battler AAA no Immutable X",
    "shrapnel": "FPS de extração modificável na Avalanche",
    "ev_io": "FPS baseado em navegador com play-to-earn",
    "gnosis_card": "Cartão Visa auto-custodial na Gnosis Chain",
    "holyheld": "Cartão de débito DeFi com recursos de rendimento",
    "fusepay": "Cartão de gastos crypto na rede Fuse",
    "loopcrypto": "Faturamento e assinaturas crypto recorrentes",
    "reveel": "Divisão automatizada de receita e royalties",
    "splits": "Protocolo de divisão de pagamentos on-chain",
    "four_meme": "Launchpad de moedas meme BNB Chain com lançamento justo",
    "sunpump": "Launchpad de moedas meme Tron com curva de vínculo",
    "moonshot": "Descoberta e negociação de tokens meme Solana",
    "ape_store": "Plataforma de lançamento justo de moedas meme Ethereum",
    "believe": "Plataforma de lançamento de tokens sociais no Solana",
    "virtuals": "Plataforma de lançamento e gaming de tokens de agente IA",
    "clanker": "Lançamento de tokens nativo do Farcaster na Base",
    "dexscreener_moonshot": "Descoberta e analíticas de moedas meme em tendência",
    "lfg_launchpad": "Plataforma oficial de lançamento de tokens do Jupiter",
    "starter": "Plataforma de IDO e incubadora multi-chain",
    "impossible_finance": "Launchpad multi-chain com níveis de staking",
    "gamefi_launchpad": "Plataforma IGO e IDO focada em gaming",
    "kommunitas": "Launchpad descentralizado alimentado por comunidade",
    "red_kite": "Launchpad multi-chain da PolkaFoundry",
    "enjinstarter": "Launchpad de gaming e metaverso",
    "trustpad": "Launchpad multi-chain com sistema de níveis",
    "spores": "Launchpad de NFT e tokens multi-chain",
    "bullperks": "Launchpad multi-chain apoiado por VC",
    "decubate": "IDO multi-chain com vesting incorporado",
    "gagarin": "Launchpad do ecossistema TON via Telegram",
    "tonstarter": "Launchpad premier para blockchain TON",
    "raydium_acceleraytor": "Plataforma de lançamento de tokens da Raydium no Solana",
    "meteora_dlmm": "Market maker de liquidez dinâmica para lançamentos de tokens",
    "orca_whirlpools": "Liquidez concentrada para lançamentos de tokens Solana",
    "legion": "Launchpad Solana primeiro a comunidade",
    "armada": "Infraestrutura de staking e validadores Solana",
    "streamflow": "Vesting de tokens e pagamentos por streaming",
    "vestinglab": "Infraestrutura de vesting de tokens multi-chain",
    "switchboard": "Oráculo descentralizado para chains Solana e Move",
    "dia": "Plataforma de oráculo transparente e personalizável",
    "tellor": "Oráculo sem permissões com mecanismo de disputa e staking",
    "symbiotic_restaking": "Protocolo de restaking modular sem permissões",
    "karak": "Restaking universal para segurança multi-chain",
    "ether_fi": "Restaking líquido não-custodial com eETH",
    "swell": "Staking e restaking líquido com swETH",
    "beefy": "Otimizador de rendimento auto-composto multi-chain",
    "equilibria": "Rendimentos aumentados para pools Pendle",
    "railgun": "DeFi privado com zk-SNARKs em chains EVM",
    "privacy_pools": "Protocolo de mistura de transações preservando privacidade",
    "aztec": "Privacidade programável com zk-rollup",
    "nocturne": "Camada de conta privada para Ethereum",
    "umbra": "Pagamentos com endereços ocultos em chains EVM",
    "labyrinth": "Privacidade conforme para instituições",
    "elusiv": "Pagamentos privados conformes no Solana",
    "zcash": "Blockchain de privacidade nativa com transações blindadas",
    "space_and_time": "Armazém de dados verificável com provas ZK",
    "allium": "Plataforma de dados blockchain empresarial",
    "sentio": "Observabilidade e monitoramento multi-chain",
    "tensor": "Negociação NFT profissional no Solana",
    "hyperspace": "Agregador e marketplace NFT no Solana",
    "tradeport": "Marketplace NFT para Sui e Aptos",
    "campfire": "Marketplace NFT na Avalanche",
    "paintswap": "Marketplace NFT no Fantom e Sonic",
    "defillama_yields": "Comparação de farming de rendimento cross-chain",
    "defilabs": "Rastreamento de baleias e dinheiro inteligente",
    "chainanalytics": "Dashboards de dados blockchain personalizados",
    "forta": "Rede de detecção de ameaças em tempo real",
    "code4rena": "Concursos de auditoria alimentados por comunidade",
    "sherlock": "Concursos de auditoria com cobertura de exploits",
    "cookie3": "Cookie3 - Analíticas blockchain",
    "chainbeat": "ChainBeat - Analíticas blockchain",
    "bitquery": "Bitquery - Analíticas blockchain",
    "whale_alert": "Alertas de transações grandes em tempo real entre blockchains",
    "intotheblock": "IntoTheBlock - Analíticas blockchain",
    "laevitas": "Laevitas - Analíticas blockchain",
    "kaiko": "Kaiko - Analíticas blockchain",
    "amberdata": "Amberdata - Analíticas blockchain",
    "blockpour": "Blockpour - Analíticas blockchain",
    "debridge_dln": "deBridge DLN - Ponte cross-chain",
    "meson_finance": "Meson - Ponte cross-chain",
    "layerswap": "Layerswap - Ponte cross-chain",
    "router_protocol": "Router Protocol - Ponte cross-chain",
    "nitro_bridge": "Nitro Bridge - Ponte cross-chain",
    "portal_bridge_wormhole": "Portal Bridge - Ponte cross-chain",
    "celer_im": "Celer IM - Ponte cross-chain",
    "multichain_anycall": "Multichain AnyCall - Ponte cross-chain",
    "hyperlane_bridge": "Hyperlane - Ponte cross-chain",
    "connext_amarok": "Connext Amarok - Ponte cross-chain"
}

print("Translation dictionaries created successfully!")
print(f"Spanish translations: {len(spanish_translations)} entries")
print(f"Portuguese translations: {len(portuguese_translations)} entries")
